// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Black_Ops_One, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Providers } from "@/components/providers/Providers";
import ClientLayoutWrapper from "@/components/providers/ClientLayoutWrapper";

const blackOpsOne = Black_Ops_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-black-ops",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: {
    default: "Xylo Tech Solutions | Premium Web Architecture",
    template: "%s | Xylo",
  },
  description:
    "We architecture high-performance websites, premium software, and next-gen intelligent mobile ecosystems.",
  keywords: [
    "Software Company",
    "Web Architecture",
    "Next.js 15",
    "App Development",
    "Xylo",
  ],
  authors: [{ name: "Xylo Team" }],
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title: "Xylo Tech Solutions",
    description: "Next-Gen Software & Intelligent Web Architecture",
    url: "https://xylo.co", // Domain name will be added soon
    siteName: "Xylo",
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${blackOpsOne.variable} ${inter.variable}`}>
      <body className="bg-black text-white antialiased">
        <Providers>
          {/* <Navbar /> */}
          <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  );
}
